### PR TITLE
Pubudu chatbot

### PR DESCRIPTION
**Pull request by pubba1998**
I create the chatbot UI design for the petstore website and also there is a file call chatbot.php another UI design please have look on both files.

### CODE REVIEW

**Comment by ClydeLiu1** [comment]
❤

**Comment by pubba1998** [comment]
chatbot UI design

**Comment by ClydeLiu1** [comment]
👅💦

**Comment by LUJ13** [comment]
🤭

**Comment by balarammahato** [comment]
you can push your file to master.

**Pull request closed without merging**
